### ISSUE TITLE
Running script successful but doesn’t appear correctly 

### ISSUE THREAD

**Issue by Mastercrafta** [leon47331/scriptable-news-rss-widget#2]
Hi, I’ve managed to get the script so it catches the BBCRSS newsfeed successfully, but it doesn’t display correctly. Please see screenshots. It’s also unable to be added as a available widget on the lock screen. Any help would be greatly appreciated, fantastic script!
![IMG_0016](https://github.com/user-attachments/assets/dc7f0adc-199a-4393-bfe5-942fa2da04d8)
![IMG_0017](https://github.com/user-attachments/assets/61f568c6-57d6-4f75-be8c-20eb06216f04)

**Comment by leon47331** [comment]
Hi @Mastercrafta!
Thank you for trying my widget!

Can you give me the URL you wanna use with this widget? So I can try it myself 😊

**Comment by Mastercrafta** [comment]
No worries! The feed is http://feeds.bbci.co.uk/news/uk/rss.xml

It does resolve to the correct site when you click the widget, juts doesn’t display correctly or is seen as an available app for the Lock Screen.
Sent from my iPhone

On 19 Jul 2024, at 11:04, Leon ***@***.***> wrote:

﻿

Hi @Mastercrafta<https://github.com/Mastercrafta>!
Thank you for trying my widget!

Can you give me the URL you wanna use with this widget? So I can try it myself 😊

**Comment by Mastercrafta** [comment]
UPDATE: Hi Leon, this is now appearing and able to be added to my Lock Screen. Unfortunately it still displays incorrectly. Could you take a look at the script? I can’t see any notable errors. 
![Uploading IMG_0018.jpeg…]()

**Comment by Mastercrafta** [comment]
UPDATE: Hi Leon, this is now appearing and able to be added to my Lock Screen. Unfortunately it still displays incorrectly. Could you take a look at the script? I can’t see any notable errors.
![IMG_0018](https://github.com/user-attachments/assets/7fba0a4c-8345-48a1-b16e-68f8652e3d56)
![IMG_0019](https://github.com/user-attachments/assets/71959a63-f81c-4e54-962d-d9466e23dbdc)
![IMG_0020](https://github.com/user-attachments/assets/e51050c1-e286-491f-954c-f67a66642407)

**Comment by leon47331** [comment]
Hi @Mastercrafta,
I am happy to hear that you were able to add the widget to your lock screen. :)
I need to commit a new version of the script to get rid of the "CDATA" string. I already tried the new version and the weird CDATA string is gone.
Commit should be online within an hour :)

Let me know if it's working for you as well!!!

**Comment by leon47331** [comment]
@Mastercrafta [v1.1.1](https://github.com/leon47331/scriptable-lockscreen-rss-widget/releases/tag/v1.1.1) is up!
It should be solved now :)

**Comment by Mastercrafta** [comment]
Leon that’s amazing. It’s working and displaying correctly now. Thanks so much for your help. Brilliant app!
Sent from my iPhone

On 19 Jul 2024, at 14:14, Leon ***@***.***> wrote:

﻿

@Mastercrafta<https://github.com/Mastercrafta> v1.1.1<https://github.com/leon47331/scriptable-lockscreen-rss-widget/releases/tag/v1.1.1> is up!
It should be solved now :)

**Comment by leon47331** [comment]
I'm so happy that I was able to help you!!! :)
I hope you like my widget and enjoy it :)
